# Generated by Django 2.2 on 2021-06-02 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='is_Staff',
            new_name='is_staff',
        ),
    ]
